# 日志相关
log:
  # 日志输出目录
  logPath: "./log"
  # 日志命名
  logName: "cpp_core.log"
  # 不做限制：-1；DEBUG：0；INFO：1；WARN：2；ERROR：3
  logLevel: -1
  # 按大小轮转(Byte)
  rotateBySize: 1024
  # 按日期轮转
  rotateByDate: true

# reactor相关
reactor:
  # 主reactor最大事件数量
  masterMaxEvent: 10
  # 主reactor超时时间(ms)
  masterTimeout: -1
  # 从reactor最大事件数量
  slaveMaxEvent: 10
  # 从reactor超时时间(ms)
  slaveTimeout: -1
  # 主从reactor
  useSlave: false

# 控制台相关
console:
  # 控制台监听ip
  consoleListenIp: "127.0.0.1"
  # 控制台监听port
  consoleListenPort: 6700
  # 控制台超时时间(s)
  consoleTimeout: 30
  # 控制台数量上线(防止恶意攻击)
  consoleMaxCount: 1
  # 是否打开控制台
  useConsole: true
