# 日志相关
log:
  # 日志输出目录, 必须是绝对路径
  logPath: "/home/muci/myutils/bin/log"
  # 日志命名
  logName: "cpp_core.log"
  # DEBUG：0；INFO：1；WARN：2；ERROR：3；DEFAULT：INFO
  logLevel: -1
  # 保存日志数量
  logFileCount: 3
  # 按大小轮转(MB)
  rotateBySize: 0
  # 按日期轮转
  rotateByDate: true
  # 异步模式
  asyncMode: true
  # 异步队列大小
  asyncQueueSize: 8192
  # 异步线程数
  asyncThreadSize: 1

# reactor相关
reactor:
  # reactor数量
  reactorCount: 1
  # reactor最大事件数量
  reactorMaxEvent: 10
  # reactor超时时间(ms)
  reactorTimeout: -1

# 控制台相关
console:
  # 控制台监听ip
  consoleListenIp: "127.0.0.1"
  # 控制台监听port
  consoleListenPort: 6700
  # 控制台超时时间(s)
  consoleTimeout: 30
  # 控制台数量上线(防止恶意攻击)
  consoleMaxCount: 1
  # 是否打开控制台
  useConsole: true

# 进程相关
process:
  # 开启守护进程模式
  daemonMode: false
  # coredump软上限(默认约2GB)
  coreLimitCur: 2000000000
  # coredump硬上限(默认约2GB)
  coreLimitMax: 2000000000

